version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    env_file: .env
  api:
    build: .
    container_name: api
    ports:
        - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_NAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    volumes:
      - .:/api
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
  client:
    build: ./client
    container_name: client
    ports:
        - "3000:3000"
    network_mode: host
    stdin_open: true
    tty: true
