# Generated by Django 4.0.5 on 2022-06-11 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_remove_newsitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг категории')),
            ],
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(verbose_name='Текст Новости'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='headline',
            field=models.CharField(max_length=255, verbose_name='Заголовок новости'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория'),
        ),
    ]
