# Generated by Django 4.0.5 on 2022-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsitem_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='client/src/images/news/', verbose_name='Изображение'),
        ),
    ]
