# Generated by Django 4.0.5 on 2022-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/news/', verbose_name='Изображение'),
        ),
    ]
